[package]
name = "room_101"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "server"
path = "src/bin/server.rs"

[[bin]]
name = "client"
path = "src/bin/client.rs"

[dependencies]
iroh = "0.91.1"
miette = "7.6.0"
thiserror = "2.0.12"
tokio = { version = "1.47.1", features = ["full"] }
