[package]
name = "room_101"
version = "0.1.0"
edition = "2024"

[dependencies]
iroh = "0.91.1"
iroh-gossip = "0.91.0"
miette = { version = "7.6.0", features = ["fancy"] }
thiserror = "2.0.12"
tokio = { version = "1.47.1", features = ["full"] }
hex = "0.4"
surrealdb = { version = "2.3.7", features = ["kv-surrealkv"] }
serde = { version = "1.0.219", features = ["derive"] }
rand = "0.8.5"
